// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_xmQV9v4tPYhJv3Ic-XPUv29doAjrVZI',
    appId: '1:164844211670:web:e37b8b162b63ec238c6877',
    messagingSenderId: '164844211670',
    projectId: 'sensorbox-6ccc8',
    authDomain: 'sensorbox-6ccc8.firebaseapp.com',
    databaseURL: 'https://sensorbox-6ccc8-default-rtdb.firebaseio.com',
    storageBucket: 'sensorbox-6ccc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqy71LrmQjZjtWPRAgXLZvgZObYpBnDgE',
    appId: '1:164844211670:ios:0e1d6ff7185672a08c6877',
    messagingSenderId: '164844211670',
    projectId: 'sensorbox-6ccc8',
    databaseURL: 'https://sensorbox-6ccc8-default-rtdb.firebaseio.com',
    storageBucket: 'sensorbox-6ccc8.firebasestorage.app',
    iosBundleId: 'com.example.sensorbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqy71LrmQjZjtWPRAgXLZvgZObYpBnDgE',
    appId: '1:164844211670:ios:0e1d6ff7185672a08c6877',
    messagingSenderId: '164844211670',
    projectId: 'sensorbox-6ccc8',
    databaseURL: 'https://sensorbox-6ccc8-default-rtdb.firebaseio.com',
    storageBucket: 'sensorbox-6ccc8.firebasestorage.app',
    iosBundleId: 'com.example.sensorbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_xmQV9v4tPYhJv3Ic-XPUv29doAjrVZI',
    appId: '1:164844211670:web:31145e3546d4722a8c6877',
    messagingSenderId: '164844211670',
    projectId: 'sensorbox-6ccc8',
    authDomain: 'sensorbox-6ccc8.firebaseapp.com',
    databaseURL: 'https://sensorbox-6ccc8-default-rtdb.firebaseio.com',
    storageBucket: 'sensorbox-6ccc8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDExm4Wvrhd8hD-lfDw7m0ZmKjPcCb3UsA',
    appId: '1:164844211670:android:85b6b32915b6f3c98c6877',
    messagingSenderId: '164844211670',
    projectId: 'sensorbox-6ccc8',
    databaseURL: 'https://sensorbox-6ccc8-default-rtdb.firebaseio.com',
    storageBucket: 'sensorbox-6ccc8.firebasestorage.app',
  );

}